/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayFooter: typeof import('@layui/layui-vue')['LayFooter']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
